language: node_js
dist: trusty
env:
- PROJECT=''
- PROJECT=mainnet
- PROJECT=olympia
install:
- npm install -s -q
before_install:
- rm -rf node_modules
- npm i -g babel-cli webpack truffle-contract
after_success:
- ./env_build.sh
deploy:
  # olympia deployments
- provider: s3
  bucket: olympia-development
  secret_access_key:
    secure: wN2R97RkkSB3zjZGt/omEO9RnPyPz3oDKfLAwKioFPniDuaRspJoCJhkpDRrqqTcRSHnjsmgv0DILj/JCVZ9u7XKr+AE1a1QGNrGuRzgKK2rcShIWl+Q8J6+SWd03UuUINEZUd5QJLesnQmly/dtBzEZl966qEL4GSviKb5S3il1TvK2tj+nVKtmunkcM2tb7oYrystklRDo19hvTBq754RXJSvo4YAM5raFUSlxHFFuYIkPrzl/HoW2d4NMtBnY7OtAErabmzOPFqYieQC3KaBxQgybuuaQHmo0+r6aSDTKpxOyRT/kmWvt4PdUl5FdC2B75lJEFeuJZDsr9kRRXmqa93JywHsc4ZzL2yNcN3MsBN3Xos9VxrM7Jf30UNZUNmorE2hPaDe5gjnjmfkQEQe/Y0tvImgMdeC0N69oRIPtXCRfZtnXEgI+6zG2/0ghj/0dtADsm4WwnpEx8SEeBjZOVqnXayplDb7RUy/H7opVXYvhw67jRHRwXVfLZdMIqGXpMZ+FWbDd969Fv0t06N7HRjE1tGMsPvpg6B9Tuv/cBg1CPLYw5okwSiSYfzY8EzAMndr0nGVJjf/VUnU0eSbfeGIXSxedaNK28U1lYW9Xdwi2oLNmQaGp2nyyySYcyH49dUoXUlwvFHmNPh4xXPGfaEjUAvXXK6NyQBsWSJM=
  access_key_id:
    secure: J3V9XlqZwJtSmuUSY+j5wVOEMfrTeYISnjSCT0oOPqgBr06UF52VyaykSW6xUV4N4lKRwbiUp5Y0mkPbg3Sdwz9n24bQr0hKu3GoyMRgFnSSv0XbyFI4dhwCPX3xiFplNt9NqTw2/673ohRMrZEe1GnxxbcPZfBglQz90x/Tt2wRKn9aXnq2NDfZ8Y42vMA1EknkG/Koyw9o33u917zIsoWhIINKtkRC/zovvuGWONmFLu+i1JRFP08GflMqd1uEBhcwj2XHKtgB8Q6/hISxBaFH+RhyfhWY0hEEfuRgDYvxesWoDNGRkJC4SB0lkQ40mdAMOp4xShzsH9HhanLMuNZt6GsMsFQcc4tkFmEsxpyLlwGIL5WKOsHsWLHxyGsKyqqh6ALTlFXxX73CE83A1xUDBhrZQBuam3XC7rWBzYl6mUzvvYmulI7rR1VsYrHD8RqFKikdHNR4Uzp+h2KEDkxZBHI5JUOK4HC7rrQO9dgaM4Cd5lUcEYY5i0CmusoUUWQriOE5QBBnfv1hJrb2SsUF1m7bFSRcl+NL5wtfZooert6ZlA//08BgQGDn3XQHgiOfqlWMOPKxg1m9OW3PMB8bEuy51xwqIdJFBf3Q99yg9GoMtO9xNlOv63GaOjKG8ZdN7m06JwD7fKTR+SBWkDqDhcShifKbbqFfSlg/tRM=
  skip_cleanup: true
  local_dir: dist
  on:
    branch: development
    condition: $PROJECT = olympia
- provider: s3
  bucket: olympia-staging
  secret_access_key:
    secure: wN2R97RkkSB3zjZGt/omEO9RnPyPz3oDKfLAwKioFPniDuaRspJoCJhkpDRrqqTcRSHnjsmgv0DILj/JCVZ9u7XKr+AE1a1QGNrGuRzgKK2rcShIWl+Q8J6+SWd03UuUINEZUd5QJLesnQmly/dtBzEZl966qEL4GSviKb5S3il1TvK2tj+nVKtmunkcM2tb7oYrystklRDo19hvTBq754RXJSvo4YAM5raFUSlxHFFuYIkPrzl/HoW2d4NMtBnY7OtAErabmzOPFqYieQC3KaBxQgybuuaQHmo0+r6aSDTKpxOyRT/kmWvt4PdUl5FdC2B75lJEFeuJZDsr9kRRXmqa93JywHsc4ZzL2yNcN3MsBN3Xos9VxrM7Jf30UNZUNmorE2hPaDe5gjnjmfkQEQe/Y0tvImgMdeC0N69oRIPtXCRfZtnXEgI+6zG2/0ghj/0dtADsm4WwnpEx8SEeBjZOVqnXayplDb7RUy/H7opVXYvhw67jRHRwXVfLZdMIqGXpMZ+FWbDd969Fv0t06N7HRjE1tGMsPvpg6B9Tuv/cBg1CPLYw5okwSiSYfzY8EzAMndr0nGVJjf/VUnU0eSbfeGIXSxedaNK28U1lYW9Xdwi2oLNmQaGp2nyyySYcyH49dUoXUlwvFHmNPh4xXPGfaEjUAvXXK6NyQBsWSJM=
  access_key_id:
    secure: J3V9XlqZwJtSmuUSY+j5wVOEMfrTeYISnjSCT0oOPqgBr06UF52VyaykSW6xUV4N4lKRwbiUp5Y0mkPbg3Sdwz9n24bQr0hKu3GoyMRgFnSSv0XbyFI4dhwCPX3xiFplNt9NqTw2/673ohRMrZEe1GnxxbcPZfBglQz90x/Tt2wRKn9aXnq2NDfZ8Y42vMA1EknkG/Koyw9o33u917zIsoWhIINKtkRC/zovvuGWONmFLu+i1JRFP08GflMqd1uEBhcwj2XHKtgB8Q6/hISxBaFH+RhyfhWY0hEEfuRgDYvxesWoDNGRkJC4SB0lkQ40mdAMOp4xShzsH9HhanLMuNZt6GsMsFQcc4tkFmEsxpyLlwGIL5WKOsHsWLHxyGsKyqqh6ALTlFXxX73CE83A1xUDBhrZQBuam3XC7rWBzYl6mUzvvYmulI7rR1VsYrHD8RqFKikdHNR4Uzp+h2KEDkxZBHI5JUOK4HC7rrQO9dgaM4Cd5lUcEYY5i0CmusoUUWQriOE5QBBnfv1hJrb2SsUF1m7bFSRcl+NL5wtfZooert6ZlA//08BgQGDn3XQHgiOfqlWMOPKxg1m9OW3PMB8bEuy51xwqIdJFBf3Q99yg9GoMtO9xNlOv63GaOjKG8ZdN7m06JwD7fKTR+SBWkDqDhcShifKbbqFfSlg/tRM=
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master
    condition: $PROJECT = olympia
# mainnet deployments
- provider: s3
  bucket: management-mainnet
  secret_access_key:
    secure: CE9Su0z1fDzf3AmeK6c2Q8UfB7n9tdSLAcy2lJHrgUbX+mxhY0kAQgg2nYSOTIZ/N9enXTFO/j5dtjliGk1Ahf0QBacYx02/548cjQxIt19G7YODQjpXeCJTQsZj4UlHyS6wmxfl1CGxViiHYkA1xHhB/IDtbrIq6ayJhpt6tCxaSMDjo38bT2u0nwX0Xt93cfTJkpdD5MuSSqRPZ/7a6LCW5YfQ/h9eXop9AkV6cvME+w7sufftb9mIOu4XDjZl65nuQ7x+qYrDrReDxwCHZQMI4SsJBWAokmbMChBm2yYQakbm3Ls3QuvNS8mgHgyOlmNgnN+fSEGvFoiUjNk9S6X80ttxp/mkoNKrvjRO92sNq7rkn6HbnhX3X2y2cclZksaCFhN9+KjWJwmMu1W52CHXciJOnViOfMTWotd69cnffqM0+ke3mI/KcK1rCakm9bVX3K0k5fUi45W7B3+H233dhwZgD50Uqi0jgO+YJUKv6hUqwa5SXYR80D4lObJbWY9BjkAg0oBi0UOp0EkMCjCRaedUG3TVcCO3uKPXlABJJbx5fEf9qROBK8E0FiCp35PBmbh/vtTb8Qk1gBEYrL2Jb+DM6u274X8BWvZ+rA3Po5IpRBIHN3EIxbs8+C0AenUVJxUhW4YPpLKCE+0/kP5xWKsIlTGVwdNWqXunZ7k=
  access_key_id:
    secure: JTcTdvhpzlwTZtU3D4ldEX97S6r4vhCJND2PvxuCSQ52NZrXB/+AJmyZ9ioYecpxaltUc8iJZ2z/B+8qgN82BG8Cgiw0KmGOS6JLQ8nCsTTM+9dmWpB6ypo76LX1SvogTl2HAjYjVINmEaVTWiIEHaXle970IAL48vr2dhk3DkK/voPekd2PjmuvHyyLGBEYVE/5qC1aDNYxvmISf+zom/7hWaCEIg6jVz5LbWeXI4YvM238HsQZRt+LyDyxFTaLlyoPUZh78Nk36itbsJd08Z7lsYr+qdMkrdQp0Qpg39IjmLz45xr5Ewl/cmOWzY3hsV8p+6Epd220cC+P2aQkKYhtbC+xpjut+TTO51woe+QLhzlupQLRrAcZP5EaB8wS7Xtjbffc6CWHTslNtrQhB9RkoSgYgBWIIRMH9eP0PrwYAvjCbONtwdz0Sk1UR8EsZPwr6maY0fnUHQRNocaDdh/RUYhrvTogBYWqHkLh0bGTxz/O4RpZnpd4yiUaXDb2+N/hZewsKGCbLm4A43WDvrIt2AkyHmPX0woyZm5XWJIX/MUGOjcXiCEgYTFUrrsxBcj4eK5WOHRpXTXMA31cWQ0pFjsP5L5eWl8j1vUMuiHXMJ4U4CHK5JmAAeWZMrhUK9ovqDP193zfI/Yb/gY8Z7Lyd490CTpkKSBR22fhzak=
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master
    condition: $PROJECT = mainnet

# testnet deployments
- provider: s3
  bucket: management-development
  secret_access_key:
    secure: i+va0a6oPvU/i5Xa5gU2o36WgoaN3W2veIxtNHtxBg0km3sl8ZGZ/umwvn7SsnsUzsyVuGi3zZfmca5qLmxngvoRhijgItOBywL2lnDwGBcH5Gxph/7401XFN8IO3SpARBS01oLSBdA4rrCPCX3CrMcNoSQNxTuAHOKsEFVplK77Cdb1Q95mbo5lmYR1bfsHj4lJe6B9bq8UN+LsIYGqX2YDzNtVeNTzaitaK8SkO23UNf1eeSndBRtWi3lfTd1K/QyR3K8sEMdFL/zvkVxduez6ABO6TvfGlceuHMhYrY0h/Unw3tDI2i5614ViByhIr+Fn214g2Ior9CPnY1mO7zfOkEy0fknHA2fSwzVQClJGJHqZsvSYvUfeuBvDAXqPLklQRXOeugBamoRc3N49sMRJoyRwyBiMK4b7VWrnJ48uPk3LwMpMYy05ToMQu1IhzuOeFbok2JhSePD/FEw98+76haFzNqQ/Zntt0UhGROtH+mvPzcbBk9CXjyeGLNmPVvwPhhOQVUnLL2vL6wWHcA8/MwfwE6HL0LwcfaBc2/sSihXWkfoABUGNt7HhHHrg1ubDAb4CSwKi5PbC67QsUwFhMVIlc7LN2s2amQn+3N4Vd4RZO8iqcwQUaaRecWsdtuvk8sym958HByr3NEhTdYjnmUJKbNSHn60Z+Zun7KE=
  access_key_id:
    secure: LjkMioUBLc8j943C186OLjPz9DbEsPJHwdJ1awqDaE0K40dQmWzROP0R3Px3qW8AOnvWmXrhGSYJWY/LbAH+NFhIbPGMlQDLp8kLYmdwW0xvxokprbP4gh2MZQoV4SOdeXSGcpR61LxFlbVubS/RARJ9tVrPtHcMgKqlF75zB65Y+4rSSkRLLIe57jAegpizmOMxdetIyQ2++KqZiZplh8+OIwyTYo/jcOHrJ6pNm+cvzPVD9Ccn0ndEsDYl2u92Ev4lKUqiNA7glfQ2BP8S3omzJhU+VESDWSZyTWsVT3jGVRU3OkHrVYsmKsDdSsVu8lBp6Bso+i5hSN+H52awYI2wYzwpxiExp6jCs6n13fslYOSMDbrtL8Zqa+cq5RCXtF5j4kaHbyhEYgo4ZKYC0r/rSDYG2Co6R8m0ortNEL6oLwAKZsphTP+jVjd0ML+XoNv3XvPfdtA6YXlsIcIh49ixfqPUWbKlTF7dFBfVePvI5bnjh13PGSFggGSrGar0h5mw4r+s8OMvmaWD1yKEd0IbRcYkqjkp0yikIymZtBr9oRDnevJZTM387p02VSxPmFKShLbj7FB4nHx9Dn0XeMVS/Io10s+xTxTD4jV5UeXZacNDTCReiCMU9JhGfQ4LdMDPJp3lIFQWc3JiGjaC8nmWMKBo6Q7L8G3cfadTDU8=
  skip_cleanup: true
  local_dir: dist
  on:
    branch: development
    condition: -z "$PROJECT"
- provider: s3
  bucket: management-staging
  secret_access_key:
    secure: i+va0a6oPvU/i5Xa5gU2o36WgoaN3W2veIxtNHtxBg0km3sl8ZGZ/umwvn7SsnsUzsyVuGi3zZfmca5qLmxngvoRhijgItOBywL2lnDwGBcH5Gxph/7401XFN8IO3SpARBS01oLSBdA4rrCPCX3CrMcNoSQNxTuAHOKsEFVplK77Cdb1Q95mbo5lmYR1bfsHj4lJe6B9bq8UN+LsIYGqX2YDzNtVeNTzaitaK8SkO23UNf1eeSndBRtWi3lfTd1K/QyR3K8sEMdFL/zvkVxduez6ABO6TvfGlceuHMhYrY0h/Unw3tDI2i5614ViByhIr+Fn214g2Ior9CPnY1mO7zfOkEy0fknHA2fSwzVQClJGJHqZsvSYvUfeuBvDAXqPLklQRXOeugBamoRc3N49sMRJoyRwyBiMK4b7VWrnJ48uPk3LwMpMYy05ToMQu1IhzuOeFbok2JhSePD/FEw98+76haFzNqQ/Zntt0UhGROtH+mvPzcbBk9CXjyeGLNmPVvwPhhOQVUnLL2vL6wWHcA8/MwfwE6HL0LwcfaBc2/sSihXWkfoABUGNt7HhHHrg1ubDAb4CSwKi5PbC67QsUwFhMVIlc7LN2s2amQn+3N4Vd4RZO8iqcwQUaaRecWsdtuvk8sym958HByr3NEhTdYjnmUJKbNSHn60Z+Zun7KE=
  access_key_id:
    secure: LjkMioUBLc8j943C186OLjPz9DbEsPJHwdJ1awqDaE0K40dQmWzROP0R3Px3qW8AOnvWmXrhGSYJWY/LbAH+NFhIbPGMlQDLp8kLYmdwW0xvxokprbP4gh2MZQoV4SOdeXSGcpR61LxFlbVubS/RARJ9tVrPtHcMgKqlF75zB65Y+4rSSkRLLIe57jAegpizmOMxdetIyQ2++KqZiZplh8+OIwyTYo/jcOHrJ6pNm+cvzPVD9Ccn0ndEsDYl2u92Ev4lKUqiNA7glfQ2BP8S3omzJhU+VESDWSZyTWsVT3jGVRU3OkHrVYsmKsDdSsVu8lBp6Bso+i5hSN+H52awYI2wYzwpxiExp6jCs6n13fslYOSMDbrtL8Zqa+cq5RCXtF5j4kaHbyhEYgo4ZKYC0r/rSDYG2Co6R8m0ortNEL6oLwAKZsphTP+jVjd0ML+XoNv3XvPfdtA6YXlsIcIh49ixfqPUWbKlTF7dFBfVePvI5bnjh13PGSFggGSrGar0h5mw4r+s8OMvmaWD1yKEd0IbRcYkqjkp0yikIymZtBr9oRDnevJZTM387p02VSxPmFKShLbj7FB4nHx9Dn0XeMVS/Io10s+xTxTD4jV5UeXZacNDTCReiCMU9JhGfQ4LdMDPJp3lIFQWc3JiGjaC8nmWMKBo6Q7L8G3cfadTDU8=
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master
    condition: -z "$PROJECT"
