language: node_js
node_js:
- node
- '8'
dist: trusty
# install:
#  - npm install -s -q
before_install:
- rm -rf node_modules
- npm i -g babel-cli webpack truffle-contract
after_success:
- |
  if [ ${TRAVIS_BRANCH} = "master" ]; then
    export NODE_ENV=production;
  else
    export NODE_ENV=development;
  fi
- npm run build
deploy:
  - provider: s3
    bucket: management-development
    secret_access_key:
      secure: pt9IEJjV8Hb+BTF3D5zqv+OggJa7pzmNxwFx1SJ10fvjlRvdPFtFvC/JueiRIYdTbOPWyHXdudRF6UvXTUx9lBjg1momS+j7nMC8fDX6mzYoDmfszdSZYC5Ew7nwUwvnhCT9/K65sMbBo9NcYZtfiLQCl+VchQPFQ/GnD7V0is+CUgt+WefabD9IG1cI4uhwDUmm1uxtl4kQWh6hUt+r5N4JLSfx6cBDLLJML6WDhonoIaPOVjYexjsjHkdWTdn9vleeRtiWPqTSH0c+tqME8rYBXDrJxIb3GAAyk5D5Yjav9I4inAnapj9RhjE6jg6Cd34WOSfGx2b+nU4EydL/jWJhGuNCgZ3HBqKOehBJMvcs7pJ1JJn4190QwPU9Q911aSyGrZRVMhkhqcW0dssEnQIL8OrVvLscuWHKjuGJWQ1Jdfvyo6OiKIghUAMUmaveWe7yCvlRwIsGjLCsGzur+/CqbssSx18CsuqG3xqs1pmn7NWvlAIhxGhtk6N6CucwKrH9Lkd+S0RC8AxnBCoBSABG0N1OOwtsvMRf8ui/RxmBvDd9v6kFqvii8NV09jMpCkpCVgiFj7WF/zzdzDa3l27jNOv1pPPu/Dk9Zm7Lqd7Jf73zxQvoz7FBJC0E4qCtE8lk+rOaSowMVcDxYu8zMAYKvlVeuaRe90JJZYbf62I=
    access_key_id:
      secure: iZynAvk8T0+lQoI7o0lC726gBQN/IWAGZJM61rzXyHL4GtCN0mxZQFMBEUSxQ6Lhaujguk94D+PGsMjmnQuo06NhNpfdzZrJEOvI/BntGxOhS66nIcZcqZV1FKwKv8zyXGj/dY1I8UGKGf0PrCCBRP34NwjMCyaECrf/hYOUTLRawRFr09ZzuHDCkP1KVP8QEEpoJxIm+DfzW8tIa+v8azYZaYlyBaRYPo2kmmQY4nbJn5sslroRV8i8/NiEG9UYSO24xqgI47kgXgw6mzpS+4OBFuPAsBRsKroacpPn/Bbmz6oSzUJyqVc6QhfP0QJ2BE9JJa3gCwcQAb7bdxm37NJL9ShG7eFCj4zCY/R78H7qqXaut/IDmvWDGGxfjX3vbDxXHdCLEPHZBXCvU0myHIJKswIrbRkat3nEPPhWRjrnTmB3RwcDFwGj3KY2XxdtG3WoJZDA+o1B4aWMh5UjYkMyWojhwOFT5mImgbTswnbCJClZFqgYTAfGmEea4+U99Ue99ojs2uCpLhLbF9UvgnxGJSQZNbme8H3j80x3KU2pbxGx3nIFceD5OaII1TF8Y9Pe6NvrSN9LMe+KkXcak+mx1pc0z2mlesw3t17xtQb6Tg3NS3Q/1DGFApQWSi8detK00GH+itq2qbqE2WyTI70U2LqzohtzBzXJqEVaYCM=
    skip_cleanup: true
    local_dir: dist
    on:
      branch: development
  - provider: s3
    bucket: management-staging
    secret_access_key:
      secure: pt9IEJjV8Hb+BTF3D5zqv+OggJa7pzmNxwFx1SJ10fvjlRvdPFtFvC/JueiRIYdTbOPWyHXdudRF6UvXTUx9lBjg1momS+j7nMC8fDX6mzYoDmfszdSZYC5Ew7nwUwvnhCT9/K65sMbBo9NcYZtfiLQCl+VchQPFQ/GnD7V0is+CUgt+WefabD9IG1cI4uhwDUmm1uxtl4kQWh6hUt+r5N4JLSfx6cBDLLJML6WDhonoIaPOVjYexjsjHkdWTdn9vleeRtiWPqTSH0c+tqME8rYBXDrJxIb3GAAyk5D5Yjav9I4inAnapj9RhjE6jg6Cd34WOSfGx2b+nU4EydL/jWJhGuNCgZ3HBqKOehBJMvcs7pJ1JJn4190QwPU9Q911aSyGrZRVMhkhqcW0dssEnQIL8OrVvLscuWHKjuGJWQ1Jdfvyo6OiKIghUAMUmaveWe7yCvlRwIsGjLCsGzur+/CqbssSx18CsuqG3xqs1pmn7NWvlAIhxGhtk6N6CucwKrH9Lkd+S0RC8AxnBCoBSABG0N1OOwtsvMRf8ui/RxmBvDd9v6kFqvii8NV09jMpCkpCVgiFj7WF/zzdzDa3l27jNOv1pPPu/Dk9Zm7Lqd7Jf73zxQvoz7FBJC0E4qCtE8lk+rOaSowMVcDxYu8zMAYKvlVeuaRe90JJZYbf62I=
    access_key_id:
      secure: iZynAvk8T0+lQoI7o0lC726gBQN/IWAGZJM61rzXyHL4GtCN0mxZQFMBEUSxQ6Lhaujguk94D+PGsMjmnQuo06NhNpfdzZrJEOvI/BntGxOhS66nIcZcqZV1FKwKv8zyXGj/dY1I8UGKGf0PrCCBRP34NwjMCyaECrf/hYOUTLRawRFr09ZzuHDCkP1KVP8QEEpoJxIm+DfzW8tIa+v8azYZaYlyBaRYPo2kmmQY4nbJn5sslroRV8i8/NiEG9UYSO24xqgI47kgXgw6mzpS+4OBFuPAsBRsKroacpPn/Bbmz6oSzUJyqVc6QhfP0QJ2BE9JJa3gCwcQAb7bdxm37NJL9ShG7eFCj4zCY/R78H7qqXaut/IDmvWDGGxfjX3vbDxXHdCLEPHZBXCvU0myHIJKswIrbRkat3nEPPhWRjrnTmB3RwcDFwGj3KY2XxdtG3WoJZDA+o1B4aWMh5UjYkMyWojhwOFT5mImgbTswnbCJClZFqgYTAfGmEea4+U99Ue99ojs2uCpLhLbF9UvgnxGJSQZNbme8H3j80x3KU2pbxGx3nIFceD5OaII1TF8Y9Pe6NvrSN9LMe+KkXcak+mx1pc0z2mlesw3t17xtQb6Tg3NS3Q/1DGFApQWSi8detK00GH+itq2qbqE2WyTI70U2LqzohtzBzXJqEVaYCM=
    skip_cleanup: true
    local_dir: dist
    on:
      branch: master
