language: node_js
node_js:
  - "8"
dist: trusty
node_js:
  node
addons:
  ssh_known_hosts:
  - olympia-staging.gnosis.pm
  - olympia-dev.gnosis.pm
before_install:
- npm i -g babel-cli webpack truffle-contract
- openssl aes-256-cbc -K $encrypted_9be2b8044ff6_key -iv $encrypted_9be2b8044ff6_iv -in .travis/deploy_key.enc -out .travis/deploy_key -d
after_success:
- chmod +x deploy.sh
- ./deploy.sh
