language: node_js
dist: trusty
env:
- | # mainnet env
  if [ ${TRAVIS_BRANCH} = "master" ]; then
    export GNOSIS_ENV=staging;
    export NODE_ENV=production;
  else
    export GNOSIS_ENV=development;
    export NODE_ENV=development;
  fi
- | # olympia env
  if [ ${TRAVIS_BRANCH} = "master" ]; then
    export GNOSIS_ENV=olympia/staging;
    export NODE_ENV=production;
  else
    export GNOSIS_ENV=olympia/development;
    export NODE_ENV=development;
  fi
install:
- npm install -s -q
before_install:
- rm -rf node_modules
- npm i -g babel-cli webpack truffle-contract
after_success:
- npm run build
deploy:
  # olympia deployments
- provider: s3
  bucket: olympia-development
  secret_access_key:
    secure: XmO28ALS4VgBGmMOQJdQKMzwPxzr5s3BsWVsK8Z0XoR/ViOH5rGol6myinEcqidy2sKEvKsEM3wAqW7eKpLXJi3YKK+1cmnpAzBlLQY7rISMpWsHOJ8Rgar9DrxsoOzqOmq24M/shrdO/Jq3NoezqWVF+pz7M2kOp/4mryJ62G7EZPEUQSAiLAK4EG86FaiiGAU+LCjH3cvgdM7LwUkcrHjHfJrrg05qDUVOfd5QCyEfUvx+sa9iOxPoFUIzqjWuHJrEN1xgbz3CcvWaLtUT1Gxldbw23yIDDPasoOZ/RcCSlbgss8myj8mCsPL/lj01nV4QNx3a3TEPcIK9sfUFgTmRkgZTtm/T39rjY1DwMk2DFa7mwIr/yWvysoRtf5Cuf6e9rPQxKuEtyKYgiYMdBlDxzsD/61/lslSCo4+Hw7FHuSsSqS7DRA6LWH2cwF/x0xp8tFnmpaugcRmZMK43vz/FVo6AM9riUDLAWuNZqfEoXqDJw0ibPKmhfvZVOhQ0PCIp4PNOauoIYPN93AyTQIQ8tqItm+YEfHP1MR/bxxUnKD8fkztcAeOTIKlv4DcPzFAr4kyHnZPvot50MOtfCf+Paetwm5wcR0IBtH32Q50/0+W62BgRlgNVu6anuzGmx2TboTCF0uySf9qops9RDZ0CF66DX/d+eMR6Jrl/jQA=
  access_key_id:
    secure: a+SpPi6jQJXzm0wJhdt4RJyd/ksS9om8IdHt2dlNsxZFxvD8NBqHKyZ0HUDB9r/+ni/vdzomQS6QfznwDrGvsIVrLaZCsdzkyTREvSXvFW3zA9MMFvf/gyNr+TXW0VMZZPC+GRhnTjWSbbFau5sGzvAb3xZKqzUIBsyb6q4r9uJfuSt4vVk427jEQMGnWK/oupw+KyE2LBUIpydPKZWVpzyX2KBAIKJzM0wZhW0lPwpXj6UNzpxi96ODTo4/rlrjBWraMr6zxfuEryXNcC4hPjrBPC9nABslZtkMuFMikIRzzYzmTExwmh2oJ3pp70HHDP1WINriMZ4XSrF6BWOQkmK0iFlaWZCenqMTQer+fzE4aKcFZgEp88c/ax8G0pKFfVRi6DtTH1iCZ9bfYHp0nvC9jtpXcYHWpWUas9mO6GG7boTZXHdlE2PKkPQUz6I3zTAkSUf1Vg8AixryeQuKnnhI2GQQ3TitK6DbN/jAvt4qV951hq7Oc4VreTu/VrcoTfyuw1x+kwUYiRk95kC5q8rIzb9qqhaknP9BKZsPd29AtiXfb9muNxjTZuuDyYkUKhC73+ZvmJfp8XBoGX95LpaiJCSBNQ5YUvEwM/uQ1E8/cj8TEdyosrofGjIQB7upbNUVYL/PbDXQXQ4O1RQ5fkjb4XOVLLNVucjfuHnn8Bg=
  skip_cleanup: true
  local_dir: dist
  on:
    branch: development
- provider: s3
  bucket: olympia-staging
  secret_access_key:
    secure: XmO28ALS4VgBGmMOQJdQKMzwPxzr5s3BsWVsK8Z0XoR/ViOH5rGol6myinEcqidy2sKEvKsEM3wAqW7eKpLXJi3YKK+1cmnpAzBlLQY7rISMpWsHOJ8Rgar9DrxsoOzqOmq24M/shrdO/Jq3NoezqWVF+pz7M2kOp/4mryJ62G7EZPEUQSAiLAK4EG86FaiiGAU+LCjH3cvgdM7LwUkcrHjHfJrrg05qDUVOfd5QCyEfUvx+sa9iOxPoFUIzqjWuHJrEN1xgbz3CcvWaLtUT1Gxldbw23yIDDPasoOZ/RcCSlbgss8myj8mCsPL/lj01nV4QNx3a3TEPcIK9sfUFgTmRkgZTtm/T39rjY1DwMk2DFa7mwIr/yWvysoRtf5Cuf6e9rPQxKuEtyKYgiYMdBlDxzsD/61/lslSCo4+Hw7FHuSsSqS7DRA6LWH2cwF/x0xp8tFnmpaugcRmZMK43vz/FVo6AM9riUDLAWuNZqfEoXqDJw0ibPKmhfvZVOhQ0PCIp4PNOauoIYPN93AyTQIQ8tqItm+YEfHP1MR/bxxUnKD8fkztcAeOTIKlv4DcPzFAr4kyHnZPvot50MOtfCf+Paetwm5wcR0IBtH32Q50/0+W62BgRlgNVu6anuzGmx2TboTCF0uySf9qops9RDZ0CF66DX/d+eMR6Jrl/jQA=
  access_key_id:
    secure: a+SpPi6jQJXzm0wJhdt4RJyd/ksS9om8IdHt2dlNsxZFxvD8NBqHKyZ0HUDB9r/+ni/vdzomQS6QfznwDrGvsIVrLaZCsdzkyTREvSXvFW3zA9MMFvf/gyNr+TXW0VMZZPC+GRhnTjWSbbFau5sGzvAb3xZKqzUIBsyb6q4r9uJfuSt4vVk427jEQMGnWK/oupw+KyE2LBUIpydPKZWVpzyX2KBAIKJzM0wZhW0lPwpXj6UNzpxi96ODTo4/rlrjBWraMr6zxfuEryXNcC4hPjrBPC9nABslZtkMuFMikIRzzYzmTExwmh2oJ3pp70HHDP1WINriMZ4XSrF6BWOQkmK0iFlaWZCenqMTQer+fzE4aKcFZgEp88c/ax8G0pKFfVRi6DtTH1iCZ9bfYHp0nvC9jtpXcYHWpWUas9mO6GG7boTZXHdlE2PKkPQUz6I3zTAkSUf1Vg8AixryeQuKnnhI2GQQ3TitK6DbN/jAvt4qV951hq7Oc4VreTu/VrcoTfyuw1x+kwUYiRk95kC5q8rIzb9qqhaknP9BKZsPd29AtiXfb9muNxjTZuuDyYkUKhC73+ZvmJfp8XBoGX95LpaiJCSBNQ5YUvEwM/uQ1E8/cj8TEdyosrofGjIQB7upbNUVYL/PbDXQXQ4O1RQ5fkjb4XOVLLNVucjfuHnn8Bg=
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master
# mainnet deployments
- provider: s3
  bucket: management-development
  secret_access_key:
    secure: i+va0a6oPvU/i5Xa5gU2o36WgoaN3W2veIxtNHtxBg0km3sl8ZGZ/umwvn7SsnsUzsyVuGi3zZfmca5qLmxngvoRhijgItOBywL2lnDwGBcH5Gxph/7401XFN8IO3SpARBS01oLSBdA4rrCPCX3CrMcNoSQNxTuAHOKsEFVplK77Cdb1Q95mbo5lmYR1bfsHj4lJe6B9bq8UN+LsIYGqX2YDzNtVeNTzaitaK8SkO23UNf1eeSndBRtWi3lfTd1K/QyR3K8sEMdFL/zvkVxduez6ABO6TvfGlceuHMhYrY0h/Unw3tDI2i5614ViByhIr+Fn214g2Ior9CPnY1mO7zfOkEy0fknHA2fSwzVQClJGJHqZsvSYvUfeuBvDAXqPLklQRXOeugBamoRc3N49sMRJoyRwyBiMK4b7VWrnJ48uPk3LwMpMYy05ToMQu1IhzuOeFbok2JhSePD/FEw98+76haFzNqQ/Zntt0UhGROtH+mvPzcbBk9CXjyeGLNmPVvwPhhOQVUnLL2vL6wWHcA8/MwfwE6HL0LwcfaBc2/sSihXWkfoABUGNt7HhHHrg1ubDAb4CSwKi5PbC67QsUwFhMVIlc7LN2s2amQn+3N4Vd4RZO8iqcwQUaaRecWsdtuvk8sym958HByr3NEhTdYjnmUJKbNSHn60Z+Zun7KE=
  access_key_id:
    secure: LjkMioUBLc8j943C186OLjPz9DbEsPJHwdJ1awqDaE0K40dQmWzROP0R3Px3qW8AOnvWmXrhGSYJWY/LbAH+NFhIbPGMlQDLp8kLYmdwW0xvxokprbP4gh2MZQoV4SOdeXSGcpR61LxFlbVubS/RARJ9tVrPtHcMgKqlF75zB65Y+4rSSkRLLIe57jAegpizmOMxdetIyQ2++KqZiZplh8+OIwyTYo/jcOHrJ6pNm+cvzPVD9Ccn0ndEsDYl2u92Ev4lKUqiNA7glfQ2BP8S3omzJhU+VESDWSZyTWsVT3jGVRU3OkHrVYsmKsDdSsVu8lBp6Bso+i5hSN+H52awYI2wYzwpxiExp6jCs6n13fslYOSMDbrtL8Zqa+cq5RCXtF5j4kaHbyhEYgo4ZKYC0r/rSDYG2Co6R8m0ortNEL6oLwAKZsphTP+jVjd0ML+XoNv3XvPfdtA6YXlsIcIh49ixfqPUWbKlTF7dFBfVePvI5bnjh13PGSFggGSrGar0h5mw4r+s8OMvmaWD1yKEd0IbRcYkqjkp0yikIymZtBr9oRDnevJZTM387p02VSxPmFKShLbj7FB4nHx9Dn0XeMVS/Io10s+xTxTD4jV5UeXZacNDTCReiCMU9JhGfQ4LdMDPJp3lIFQWc3JiGjaC8nmWMKBo6Q7L8G3cfadTDU8=
  skip_cleanup: true
  local_dir: dist
  on:
    branch: development
- provider: s3
  bucket: management-staging
  secret_access_key:
    secure: i+va0a6oPvU/i5Xa5gU2o36WgoaN3W2veIxtNHtxBg0km3sl8ZGZ/umwvn7SsnsUzsyVuGi3zZfmca5qLmxngvoRhijgItOBywL2lnDwGBcH5Gxph/7401XFN8IO3SpARBS01oLSBdA4rrCPCX3CrMcNoSQNxTuAHOKsEFVplK77Cdb1Q95mbo5lmYR1bfsHj4lJe6B9bq8UN+LsIYGqX2YDzNtVeNTzaitaK8SkO23UNf1eeSndBRtWi3lfTd1K/QyR3K8sEMdFL/zvkVxduez6ABO6TvfGlceuHMhYrY0h/Unw3tDI2i5614ViByhIr+Fn214g2Ior9CPnY1mO7zfOkEy0fknHA2fSwzVQClJGJHqZsvSYvUfeuBvDAXqPLklQRXOeugBamoRc3N49sMRJoyRwyBiMK4b7VWrnJ48uPk3LwMpMYy05ToMQu1IhzuOeFbok2JhSePD/FEw98+76haFzNqQ/Zntt0UhGROtH+mvPzcbBk9CXjyeGLNmPVvwPhhOQVUnLL2vL6wWHcA8/MwfwE6HL0LwcfaBc2/sSihXWkfoABUGNt7HhHHrg1ubDAb4CSwKi5PbC67QsUwFhMVIlc7LN2s2amQn+3N4Vd4RZO8iqcwQUaaRecWsdtuvk8sym958HByr3NEhTdYjnmUJKbNSHn60Z+Zun7KE=
  access_key_id:
    secure: LjkMioUBLc8j943C186OLjPz9DbEsPJHwdJ1awqDaE0K40dQmWzROP0R3Px3qW8AOnvWmXrhGSYJWY/LbAH+NFhIbPGMlQDLp8kLYmdwW0xvxokprbP4gh2MZQoV4SOdeXSGcpR61LxFlbVubS/RARJ9tVrPtHcMgKqlF75zB65Y+4rSSkRLLIe57jAegpizmOMxdetIyQ2++KqZiZplh8+OIwyTYo/jcOHrJ6pNm+cvzPVD9Ccn0ndEsDYl2u92Ev4lKUqiNA7glfQ2BP8S3omzJhU+VESDWSZyTWsVT3jGVRU3OkHrVYsmKsDdSsVu8lBp6Bso+i5hSN+H52awYI2wYzwpxiExp6jCs6n13fslYOSMDbrtL8Zqa+cq5RCXtF5j4kaHbyhEYgo4ZKYC0r/rSDYG2Co6R8m0ortNEL6oLwAKZsphTP+jVjd0ML+XoNv3XvPfdtA6YXlsIcIh49ixfqPUWbKlTF7dFBfVePvI5bnjh13PGSFggGSrGar0h5mw4r+s8OMvmaWD1yKEd0IbRcYkqjkp0yikIymZtBr9oRDnevJZTM387p02VSxPmFKShLbj7FB4nHx9Dn0XeMVS/Io10s+xTxTD4jV5UeXZacNDTCReiCMU9JhGfQ4LdMDPJp3lIFQWc3JiGjaC8nmWMKBo6Q7L8G3cfadTDU8=
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master
